"""Unit tests for PDF report exporter (Prompt 6.6)."""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from unittest.mock import patch

from dfat.core.models.evidence import CaseMetadata
from dfat.core.models.report import ForensicReport, JSONReport, NarrativeReport
from dfat.reporting.exporters.pdf_exporter import PDFReportExporter


def _sample_report() -> ForensicReport:
    """Build a minimal ForensicReport for export tests."""
    artefacts = [
        {
            "artefact_id": f"art-{index}",
            "category": "injected_code" if index % 2 == 0 else "registry_key",
            "suspicion_level": "critical" if index == 0 else "high",
            "relevance_score": 1.0 - (index * 0.05),
            "source_path": f"/path/{index}",
            "raw_data": {"timestamp": f"2024-01-0{index + 1}T00:00:00Z", "pid": index},
            "classification_reasoning": f"Reason {index}",
        }
        for index in range(5)
    ]
    narrative = (
        "# Investigative Summary\n\n"
        "## LLM Disclaimer\n\n"
        "DISCLAIMER: Generated by test-model (Scanlon et al., 2023).\n\n"
        "## Executive Summary\n\n"
        "Suspicious injected code observed on the host.\n\n"
        "## Key Findings\n\n"
        "- RWX memory region\n"
        "- Persistence run key\n\n"
        "## Timeline of Events\n\n"
        "T0 acquisition; T1 triage.\n\n"
        "## Indicators of Compromise\n\n"
        "| # | Indicator |\n"
        "| 1 | evil.exe |\n"
    )
    return ForensicReport(
        case=CaseMetadata(
            case_name="PDF Export Case",
            investigator="Analyst",
        ),
        json_report=JSONReport(
            evidence_id="ev-pdf-1",
            artefact_data=artefacts,
            integrity_hash="a" * 64,
            generated_at=datetime.now(UTC),
        ),
        narrative_report=NarrativeReport(
            evidence_id="ev-pdf-1",
            summary_text=narrative,
            llm_model_used="test-model",
            generation_parameters={"iocs_identified": ["evil.exe"]},
        ),
        pipeline_duration_seconds=12.5,
        stage_timings={"acquisition": 1.0, "reporting": 0.5},
        audit_metadata={
            "generated_by_user_id": "user-1",
            "pipeline_job_id": "job-9",
            "tool_version": "0.1.0",
        },
    )


def test_pdf_generation_or_fallback(tmp_path: Path) -> None:
    """Verify PDF generation succeeds, or plaintext fallback if backends missing."""
    exporter = PDFReportExporter(tmp_path)
    report = _sample_report()
    path = exporter.export(report, include_narrative=True, include_json_appendix=True)
    assert path.parent == tmp_path
    assert path.exists()
    assert path.suffix in {".pdf", ".txt"}
    assert path.stat().st_size > 100
    assert "dfat_report_" in path.name


def test_export_generates_pdf_with_sections(tmp_path: Path) -> None:
    """Verify PDF export produces a file under output_dir with expected content path."""
    test_pdf_generation_or_fallback(tmp_path)


def test_all_sections_present(tmp_path: Path) -> None:
    """Verify exported PDF/plaintext includes required investigative sections."""
    test_plaintext_fallback_when_backends_missing(tmp_path)


def test_output_file_created(tmp_path: Path) -> None:
    """Verify exporter always creates an output file on disk."""
    path = PDFReportExporter(tmp_path).export(_sample_report())
    assert path.exists()
    assert path.is_file()


def test_plaintext_fallback_when_backends_missing(tmp_path: Path) -> None:
    """Verify plaintext fallback when reportlab/weasyprint are unavailable."""
    exporter = PDFReportExporter(tmp_path)
    report = _sample_report()
    with (
        patch(
            "dfat.reporting.exporters.pdf_exporter._reportlab_available",
            return_value=False,
        ),
        patch(
            "dfat.reporting.exporters.pdf_exporter._weasyprint_available",
            return_value=False,
        ),
    ):
        path = exporter.export(report)

    assert path.suffix == ".txt"
    assert path.exists()
    text = path.read_text(encoding="utf-8")
    for section in (
        "Cover Page",
        "Table of Contents",
        "Executive Summary",
        "Key Findings",
        "Artefact Summary",
        "Timeline",
        "Indicators of Compromise",
        "Statistics",
        "Audit Trail Summary",
        "LLM Disclaimer",
        "JSON Data Appendix",
    ):
        assert section in text
    assert "PDF Export Case" in text
    assert "Scanlon et al." in text
    assert "evil.exe" in text
    assert "generated_by_user_id: user-1" in text


def test_plaintext_fallback_method_directly(tmp_path: Path) -> None:
    """Verify _generate_plaintext_fallback writes a structured text file."""
    exporter = PDFReportExporter(tmp_path)
    path = exporter._generate_plaintext_fallback(_sample_report())
    assert path.suffix == ".txt"
    assert path.parent == tmp_path
    content = path.read_text(encoding="utf-8")
    assert "PLAINTEXT FALLBACK" in content
    assert "DFAT version:" in content


def test_json_appendix_truncation(tmp_path: Path) -> None:
    """Verify JSON appendix notes truncation above 100 artefacts."""
    exporter = PDFReportExporter(tmp_path)
    report = _sample_report()
    report.json_report.artefact_data = [
        {
            "artefact_id": f"a-{i}",
            "category": "event_log",
            "suspicion_level": "low",
            "relevance_score": 0.1,
            "raw_data": {},
        }
        for i in range(120)
    ]
    with (
        patch(
            "dfat.reporting.exporters.pdf_exporter._reportlab_available",
            return_value=False,
        ),
        patch(
            "dfat.reporting.exporters.pdf_exporter._weasyprint_available",
            return_value=False,
        ),
    ):
        path = exporter.export(report, include_json_appendix=True)
    text = path.read_text(encoding="utf-8")
    assert "truncated to first 100 of 120" in text
