"""DFAT API Routes — HTTP endpoints for auth, health, evidence, and analysis."""

from dfat.api.routes import (
    ai,
    analysis,
    auth,
    cases,
    datasets,
    evaluation,
    evidence,
    evidence_management,
    health,
    knowledge,
    ml,
    monitoring,
    pipeline,
    reports,
    system,
    threat_intel,
    users,
)

__all__ = [
    "ai",
    "analysis",
    "auth",
    "cases",
    "datasets",
    "evaluation",
    "evidence",
    "evidence_management",
    "health",
    "knowledge",
    "ml",
    "monitoring",
    "pipeline",
    "reports",
    "system",
    "threat_intel",
    "users",
]
