/**
 * Relative API path map for DFAT backend (`/api/v1` prefix applied via apiBaseUrl).
 * Covers the Prompt 7 inventory plus known Prompt 6 extras used by services later.
 */
export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    REFRESH: "/auth/refresh",
    LOGOUT: "/auth/logout",
    LOGOUT_ALL: "/auth/logout-all",
    CHANGE_PASSWORD: "/auth/change-password",
  },
  USERS: {
    ME: "/users/me",
    LIST: "/users",
    BY_ID: (id) => `/users/${id}`,
    DEACTIVATE: (id) => `/users/${id}/deactivate`,
  },
  HEALTH: {
    CHECK: "/health",
    READY: "/health/ready",
    DETAILED: "/health/detailed",
  },
  CASES: {
    LIST: "/cases",
    CREATE: "/cases",
    MINE: "/cases/mine",
    BY_ID: (id) => `/cases/${id}`,
    SUMMARY: (id) => `/cases/${id}/summary`,
    OPEN: (id) => `/cases/${id}/open`,
    ACTIVATE: (id) => `/cases/${id}/activate`,
    CLOSE: (id) => `/cases/${id}/close`,
    ARCHIVE: (id) => `/cases/${id}/archive`,
    SUBMIT_REVIEW: (id) => `/cases/${id}/submit-review`,
    REOPEN: (id) => `/cases/${id}/reopen`,
    INVESTIGATORS: (id) => `/cases/${id}/investigators`,
    REMOVE_INVESTIGATOR: (caseId, userId) =>
      `/cases/${caseId}/investigators/${userId}`,
    ADD_EVIDENCE: (id) => `/cases/${id}/evidence`,
  },
  EVIDENCE: {
    REGISTER: "/evidence/register",
    INVENTORY: "/evidence/inventory",
    DETAIL: (id) => `/evidence/${id}/detail`,
    VALIDATE: (id) => `/evidence/${id}/validate`,
    VERIFY: (id) => `/evidence/${id}/verify-integrity`,
    CUSTODY: (id) => `/evidence/${id}/custody`,
    STATUS: (id) => `/evidence/${id}/status`,
    QUARANTINE: (id) => `/evidence/${id}/quarantine`,
    STATS: "/evidence/statistics",
  },
  PIPELINE: {
    RUN: "/pipeline/run",
    BY_ID: (id) => `/pipeline/${id}`,
    PROGRESS: (id) => `/pipeline/${id}/progress`,
    CANCEL: (id) => `/pipeline/${id}/cancel`,
    JOBS: "/pipeline/jobs",
    PARSERS: "/pipeline/parsers",
  },
  AI: {
    CLASSIFY: "/ai/classify",
    SUMMARIZE: "/ai/summarize",
    EXPLAIN: (id) => `/ai/explain/${id}`,
    ASK: "/ai/ask",
    HEALTH: "/ai/health",
    STATS: "/ai/stats",
    CACHE_STATS: "/ai/cache/stats",
    CACHE_CLEAR: "/ai/cache",
  },
  REPORTS: {
    LIST: "/reports",
    BY_ID: (id) => `/reports/${id}`,
    JSON: (id) => `/reports/${id}/json`,
    NARRATIVE: (id) => `/reports/${id}/narrative`,
    PDF: (id) => `/reports/${id}/export/pdf`,
    HTML: (id) => `/reports/${id}/export/html`,
    JSON_FILE: (id) => `/reports/${id}/export/json-file`,
    VERIFY: (id) => `/reports/${id}/verify`,
    COMPARE: "/reports/compare",
    CUSTODY: (id) => `/reports/${id}/custody`,
    AUDIT_TRAIL: (id) => `/reports/${id}/audit-trail`,
  },
  EVALUATION: {
    BENCHMARK_RUN: "/evaluation/benchmark",
    BENCHMARK_RESULTS: "/evaluation/benchmark/results",
    BENCHMARK_RESULT: (id) => `/evaluation/benchmark/results/${id}`,
    BENCHMARK_PERFORMANCE: "/evaluation/benchmark/performance",
    BENCHMARK_DATASETS: "/evaluation/benchmark/datasets",
    USABILITY_RESPOND: "/evaluation/usability/respond",
    USABILITY_QUESTIONNAIRE: "/evaluation/usability/questionnaire",
    USABILITY_RESULTS: "/evaluation/usability/results",
    USABILITY_EXPORT: "/evaluation/usability/export",
    USABILITY_DELETE: "/evaluation/usability/responses",
  },
  DATASETS: {
    LIST: "/datasets",
    STATISTICS: "/datasets/statistics",
    SCAN: "/datasets/scan",
    BY_ID: (id) => `/datasets/${id}`,
    REINDEX: (id) => `/datasets/${id}/reindex`,
    REFRESH: (id) => `/datasets/${id}/refresh`,
    DELETE: (id) => `/datasets/${id}`,
  },
  KNOWLEDGE: {
    STATS: "/knowledge/stats",
    QUERY: "/knowledge/query",
    GRAPH_STATS: "/knowledge/graph/stats",
    IOCS: "/knowledge/iocs",
    IOC_STATS: "/knowledge/iocs/stats",
  },
  ML: {
    MODELS: "/ml/models",
    MODEL_LATEST: (name) => `/ml/models/${encodeURIComponent(name)}/latest`,
    TRAIN: "/ml/train",
    RETRAIN: "/ml/retrain",
    PREDICT: "/ml/predict",
    EXPERIMENTS: "/ml/experiments",
    EXPERIMENT: (id) => `/ml/experiments/${id}`,
  },
  THREAT_INTEL: {
    SUMMARY: "/threat-intel/summary",
    SCAN: "/threat-intel/scan",
    MITRE: "/threat-intel/mitre",
    YARA_RULES: "/threat-intel/yara/rules",
    SIGMA_RULES: "/threat-intel/sigma/rules",
  },
  SYSTEM: {
    STARTUP: "/system/startup",
    STATUS: "/system/status",
    RESOURCES: "/system/resources",
    RESOURCE_ALERTS: "/system/resources/alerts",
    TASKS: "/system/tasks",
    RESTART_TASK: (name) => `/system/tasks/${encodeURIComponent(name)}/restart`,
    CAPABILITIES: "/system/capabilities",
    DIAGNOSTICS: "/system/diagnostics",
  },
};
