"""Human-readable narrative assembler (supplementary investigative aid)."""

from __future__ import annotations

from collections import defaultdict
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Optional
from uuid import uuid4

from jinja2 import Environment, FileSystemLoader, select_autoescape

from dfat.core.models.artefact import RankedArtefact
from dfat.core.models.report import NarrativeReport

_DISCLAIMER_TEMPLATE = (
    "This narrative was generated by {model} and should be verified against "
    "the structured JSON artefact data. LLM outputs may contain inaccuracies."
)


class NarrativeAssembler:
    """Assemble a disclaimer-wrapped investigative narrative report."""

    def __init__(self, template_dir: Path) -> None:
        """Initialise the narrative assembler.

        Args:
            template_dir: Directory containing ``narrative_template.j2``.
        """
        self._template_dir = template_dir
        self._env = Environment(
            loader=FileSystemLoader(str(template_dir)),
            autoescape=select_autoescape(enabled_extensions=()),
        )

    def assemble(
        self,
        summary_text: str,
        llm_model: str,
        generation_params: dict[str, Any],
        ranked_artefacts: list[RankedArtefact],
        *,
        evidence_id: str,
        case_name: str = "Unknown Case",
    ) -> NarrativeReport:
        """Assemble a structured narrative document.

        Args:
            summary_text: LLM-generated or fallback summary body.
            llm_model: Model identifier used for generation.
            generation_params: Generation parameter snapshot.
            ranked_artefacts: Triaged artefacts for appendix/statistics.
            evidence_id: Source evidence identifier.
            case_name: Case name for the title block.

        Returns:
            Populated ``NarrativeReport``.
        """
        disclaimer = self._add_disclaimer("", llm_model).strip()
        statistics_appendix = self._generate_statistics_appendix(ranked_artefacts)
        findings = self._group_by_category(ranked_artefacts)
        generated_at = datetime.now(UTC)
        report_id = str(uuid4())

        template = self._env.get_template("narrative_template.j2")
        rendered = template.render(
            case_name=case_name,
            generated_at=generated_at.isoformat(),
            evidence_id=evidence_id,
            report_id=report_id,
            disclaimer=disclaimer,
            executive_summary=summary_text.strip() or "_No summary provided._",
            findings_by_category=findings,
            timeline=self._extract_timeline(ranked_artefacts),
            statistics_appendix=statistics_appendix,
            llm_model=llm_model,
            generation_params=generation_params,
            artefact_count=len(ranked_artefacts),
        )

        return NarrativeReport(
            report_id=report_id,
            evidence_id=evidence_id,
            summary_text=rendered,
            llm_model_used=llm_model,
            generation_parameters=dict(generation_params),
            generated_at=generated_at,
        )

    def _add_disclaimer(self, summary: str, model: str) -> str:
        """Prepend the LLM hallucination disclaimer.

        Args:
            summary: Optional summary body.
            model: Model identifier.

        Returns:
            Disclaimer text, optionally followed by the summary.
        """
        disclaimer = _DISCLAIMER_TEMPLATE.format(model=model)
        if summary.strip():
            return f"{disclaimer}\n\n{summary.strip()}"
        return disclaimer

    def _generate_statistics_appendix(
        self,
        ranked: list[RankedArtefact],
    ) -> str:
        """Build a text-formatted statistics appendix.

        Args:
            ranked: Ranked artefacts.

        Returns:
            Multi-line statistics table as plain text.
        """
        by_category: dict[str, int] = defaultdict(int)
        by_level: dict[str, int] = defaultdict(int)
        for artefact in ranked:
            by_category[artefact.category.value] += 1
            by_level[artefact.suspicion_level.value] += 1

        lines = [
            f"Total artefacts: {len(ranked)}",
            "",
            "By category:",
        ]
        for key, count in sorted(by_category.items()):
            lines.append(f"  - {key}: {count}")
        lines.append("")
        lines.append("By suspicion level:")
        for key, count in sorted(by_level.items()):
            lines.append(f"  - {key}: {count}")
        return "\n".join(lines)

    @staticmethod
    def _group_by_category(
        ranked: list[RankedArtefact],
    ) -> dict[str, list[RankedArtefact]]:
        """Group ranked artefacts by category name."""
        grouped: dict[str, list[RankedArtefact]] = defaultdict(list)
        for artefact in ranked:
            grouped[artefact.category.value].append(artefact)
        return dict(sorted(grouped.items()))

    @staticmethod
    def _extract_timeline(ranked: list[RankedArtefact]) -> list[str]:
        """Best-effort timeline lines from artefact raw_data timestamps."""
        events: list[str] = []
        for artefact in ranked:
            raw = artefact.raw_data
            stamp: Optional[Any] = (
                raw.get("timestamp")
                or raw.get("create_time")
                or raw.get("last_visit_time")
                or raw.get("modified_time")
            )
            if stamp is None:
                continue
            events.append(
                f"{stamp} | {artefact.category.value} | "
                f"{artefact.source_path or artefact.artefact_id}"
            )
        return events
